traefik/faency

src/components/Chip.story.tsx, src/components/Chip.tsx
=> fix: Chip should be a directive from an inline element

.gitignore, src/components/Button.tsx
=> fix: grey background color for default buttons on windows

src/components/Loading.story.tsx, src/components/Loading.tsx
=> Add <Loading> component

src/components/Chip.tsx
=> fix: chip are now using nowrap

src/components/ToggleButton.story.tsx, src/components/ToggleButton.tsx
=> Add ToggleButtonGroup component

package-lock.json, package.json, src/components/Nav.story.tsx, src/components/Nav.tsx, src/components/SubNav.tsx, src/types/index.d.ts
=> fix: correct NavItem type issue + import of styled-system

package-lock.json, package.json
- NavItem type issue + import of styled-system (https://github.com/containous/faency/pull/32)
=> chore: bump to v0.2.1

src/components/Chip.story.tsx, src/components/Chip.tsx
=> feat: add red color variant to Chip component

package-lock.json, package.json
- Add red color variant to Chip component (#34)
- Add positive, warning and negative colors (#37)
=> chore: bump to v0.2.2

package-lock.json, package.json
- Closing backticks are not displaying properly (#41)
=> chore: bump to v0.3.1

src/breakpoints.ts, src/components/Nav/Nav.story.tsx, src/components/Nav/Nav.tsx, src/components/Nav/components/Menu.tsx, src/components/Nav/components/MenuButton.tsx, src/components/Nav/components/MenuIcon.tsx, src/components/Nav/components/NavIcon.tsx, src/components/Nav/index.ts, src/components/Nav/utils/uuidv4.ts, src/components/SubNav.story.tsx, src/components/SubNav.tsx
=> Nav and SubNav components are now responsive

src/components/Radio.story.tsx, src/components/Radio.tsx
=> feat: Add Radio component

.gitignore, src/components/Checkbox.story.tsx, src/components/Checkbox.tsx, src/types/index.d.ts
=> Add Checkbox component

packages/website/src/App.js, packages/website/src/components/Divider.js, packages/website/src/components/MenuToggle.js, packages/website/src/wrapPageElement.js
=> fix: add MenuToggle component to toggle mobile doc menu

packages/faency/src/components/DropdownMenu.story.tsx, packages/faency/src/components/DropdownMenu.test.tsx, packages/faency/src/components/DropdownMenu.tsx, packages/faency/src/components/Menu.story.tsx, packages/faency/src/components/Menu.tsx, packages/faency/src/components/ToggleButton.test.tsx, packages/faency/src/index.ts, packages/website/src/docs/dropdown.mdx, packages/website/src/docs/menu.mdx
Added a separated Menu component once it can be used on other use cases as well.
Also fixed all the unit tests to support the theme context, and added the test run to the CI.
=> Add Dropdown and Menu components

packages/website/src/App.js
=> fix: make active state works in prod

packages/faency/src/components/Skeleton.story.tsx, packages/faency/src/components/Skeleton.tsx, packages/faency/src/index.ts, packages/website/src/docs/skeleton.mdx
=> feat: add skeleton loading components

packages/website/src/wrapPageElement.js
=> Add Theme Switcher to Docs Website

packages/faency/src/components/Avatar..test.tsx, packages/faency/src/components/Avatar.story.tsx, packages/faency/src/components/Avatar.test.tsx, packages/faency/src/components/Avatar.tsx, packages/faency/src/dark-theme.ts, packages/faency/src/index.ts, packages/faency/src/theme.ts, packages/website/src/docs/avatar.mdx, packages/website/src/templates/doc-page.js
=> Add Avatar component

packages/faency/src/components/Loading.story.tsx, packages/faency/src/components/Loading.tsx, packages/website/src/docs/Loading.mdx
This PR adds the ability to customize the Loader component color.
=> Add ability to set custom color for Loading bar

packages/faency/src/components/Nav/Nav.tsx
=> Fix Flex direction on Tablet width

packages/faency/package.json, packages/faency/src/components/Avatar.tsx, packages/faency/src/components/AvatarLink.story.tsx, packages/faency/src/components/AvatarLink.test.tsx, packages/faency/src/components/AvatarLink.tsx, yarn.lock
Add `AvatarLink` component and avoid hover style on `Avatar` one.
=> Add AvatarLink component

packages/faency/src/components/CardLink.tsx
=> Fix CardLink missing border

.github/workflows/pr.yml
This PR fix the github action name
=> Fix github action name

components/Dialog/Dialog.stories.tsx, components/Dialog/Dialog.tsx
This PR aims to make the Dialog component more responsive when the content is too big.
https://user-images.githubusercontent.com/38889364/135492463-fe021832-7367-46de-8042-a0686988f439.mov
=> chore: add overflow auto to Dialog component

components/Input/Input.tsx, components/TextField/TextField.tsx
cf. feedback in this PR merged too early traefik#160
=> Input feedback

components/Switch/Switch.stories.tsx, components/Switch/Switch.themes.ts, components/Switch/Switch.tsx, components/Switch/index.tsx, index.ts, stitches.config.ts
#145 
- Run storybook
- Check story : Switch
- Disabled state : not part of mockups
- Focus state: not part of mockups. Should we prefer an elevation ?
- Hovered state: not part of mockups. Should we prefer an elevation ?
- Sizes: already existing and updated without mockups
Rest follows design preco from the issue
blocked by https://github.com/traefik/faency/pull/164
=> Add switch component

stitches.config.ts, stories/colors.stories.tsx
Fix https://github.com/traefik/faency/issues/187
=> fix: import right colors const in colors story

components/FaencyProvider.tsx
This was a console warning. I checked stitches docs: https://stitches.dev/docs/api#globalcss
=> fix: FaencyProvider, global styles not called properly

components/Select/Select.tsx
Rework Select variants and props.
Closes #198
=> fix: Select, proper variants and props typing

components/Skeleton/Skeleton.stories.tsx, components/Skeleton/Skeleton.tsx
Skeleton, add badge variant and story
https://user-images.githubusercontent.com/3367393/146020696-3aceec54-f4ff-415f-827e-0805a003ee2d.mp4
=> feat: skeleton, add badge variant

components/Bubble/Bubble.stories.tsx, components/Bubble/Bubble.tsx
Add `size` variant `x-large` to `Bubble`
Closes #228 
https://user-images.githubusercontent.com/3367393/146243810-325ef987-dc66-40d0-9f61-b537e5aaee63.mp4
=> feat: bubble update largest size

components/Accordion/Accordion.stories.tsx, components/Accordion/Accordion.themes.ts, components/Accordion/Accordion.tsx, components/Accordion/index.ts, index.ts, package-lock.json, package.json, stitches.config.ts
Add Accordion component
Closes #238 
Add `@radix-ui/react-accordion` version `0.1.5`
Some typing issues...
I set `any` type everywhere I couldn't figure out what was the cause of type issue
=> chore: Accordion

components/Accordion/Accordion.stories.tsx, components/Accordion/Accordion.themes.ts, components/Accordion/Accordion.tsx, stitches.config.ts
Updates Accordion styles to simplify future integration.
No system design nor issue, :shrug: 
1. Updates Accordion styles
2. Adds Divider semantic color for Accordion usage
NB: change °2 could be split into a separate PR, but it really feels like doing something bad in this PR to improve in another one.
=> feat: accordion styles

package.json
- Release Accordion component with updated styles
- Ship fixes
[page](https://github.com/traefik/faency/commits/master)
None
- [accordion component](https://github.com/traefik/faency/commit/e2457173fef2bd23d5d08e64bb92908a4b7629c9)
- [accordion styles](https://github.com/traefik/faency/commit/23eeaff3eb97fd4c348fff9ac33710d8b86a1e59)
- [bubble update largest size](https://github.com/traefik/faency/commit/2656d23cdc4a13dd022a761999b9ab447df7be87)
- [skeleton add badge variant](https://github.com/traefik/faency/commit/eeca841e1079d26f81525cba3c675aa995bb12e6)
- [badge cleanup](https://github.com/traefik/faency/commit/216fb736e17f791e5c35fadd3ada506991105f9f)
- [select caret, option overflow management](https://github.com/traefik/faency/commit/7b9288b5f7ae0dc6bf9aebb6c23986be7b5b4474)
- …
=> chore: release v1.0.0-6

package.json
[page](https://github.com/traefik/faency/commits/master)
- [update stitches](https://github.com/traefik/faency/commit/70c6f17972ec35a216045bd22c241dfa235b9151)
- [release notes](https://github.com/modulz/stitches/releases/tag/v1.2.6) : only bugfixes
- [Th layout broken by label capitalize change](https://github.com/traefik/faency/commit/4b7262a7a6c1933afd229cac83a4f3d5c2c6886b)
=> chore: release v1.0.0-7

index.ts
Expose `VariantProps` for reuse in consuming projects
=> feat: expose VariantProps

package-lock.json, package.json
[page](https://github.com/traefik/faency/commits/master)
- [radio accordion component](https://github.com/traefik/faency/commit/099c10c713b2f7c3db55eda5416237f3af008823)
=> chore: release v1.0.0-8

package-lock.json, package.json
- https://github.com/traefik/faency/pull/265
- https://github.com/traefik/faency/pull/264
- https://github.com/traefik/faency/pull/263
- https://github.com/traefik/faency/pull/268
- [Textfield allow label component](https://github.com/traefik/faency/commit/b8437d81018a3c3d37be6483e5694409a0b3724a)
- Label, Improve form field integration
- RadioAccordion, omit `collapsible` prop
- bump node-fetch
- bump shelljs
- Label props
=> chore: release v1.0.0-9

components/Radio/Radio.tsx
transform cursor into pointer when hovering over radio button
https://user-images.githubusercontent.com/3367393/151777088-5a807d06-fad5-4447-95eb-b63c258349ed.mp4
=> feat: Radio, hover pointer

components/Table/Table.stories.tsx, components/Table/Table.themes.ts, components/Table/Table.tsx
Closes https://github.com/traefik/faency/issues/152.
Updates the Table and related components' style.
Light:
Dark:
=> chore: update Table styles

package-lock.json, package.json
- https://github.com/traefik/faency/pull/274
- https://github.com/traefik/faency/pull/237
- https://github.com/traefik/faency/pull/277
- https://github.com/traefik/faency/pull/278 (Breaking change)
=> chore: release v1.0.0-10

.storybook/preview.js
Since the latest release primary color + dark/light theme was not working
=> fix: storybook theme + primary color

package-lock.json, package.json
- https://github.com/traefik/faency/pull/282
- https://github.com/traefik/faency/pull/281
- https://github.com/traefik/faency/pull/245
=> chore: release v1.0.0-11

package-lock.json, package.json
Releasing to ship:
- https://github.com/traefik/faency/commit/9ed43215a4a9ef3c132c0ac3df004693de28c1ab
cf3e05ac9eeb58535ecd3f48d96b25f195ea8a93...9ed43215a4a9ef3c132c0ac3df004693de28c1ab
=> release: v1.0.0-12

.github/pull_request_template.md, README.md
Adds PR template. Updates `README`
There are a few specific sections for Faency, which would require more attention:
- breaking changes
- good PR checkboxes
- good review checkboxes
=> chore: add PR template

.github/pull_request_template.md, .github/workflows/release.yml, README.md, package-lock.json, package.json
Closes #180 - Adds [semantic-release](https://semantic-release.gitbook.io/semantic-release/)
Closes #170 - Adds node engine requirement following [semantic-release requirement](https://semantic-release.gitbook.io/semantic-release/support/node-version): `>=14.17.0`
Preset: [conventional-commits](https://www.conventionalcommits.org/en/v1.0.0/)
Updates README
Updates package version to `1.0.0-semantic-release` following [recommendations](https://semantic-release.gitbook.io/semantic-release/support/faq#can-i-set-the-initial-release-version-of-my-package-to-0.0.1)
Package version will be handled by `semantic-release`. The one in this project will no longer be updated. We can create an RFC if you think it would be useful to keep updating our package version on github.
| Dependency | Version …
=> chore: add semantic release, preset conventionalcommits

.github/pull_request_template.md, README.md
- Improvements to release process and how to contribute
- Also updates PR template
<details>
```markdown
```
</details>
=> docs: how to contribute, release process

components/AriaTable/AriaTable.tsx, components/Table/Table.stories.tsx, components/Table/Table.tsx
- Improves `Tfoot` `border-radii` and its `borderTop` depending on contents of `Thead` and `Tbody`
- Applies default user agent stylesheet rules on elements
https://user-images.githubusercontent.com/3367393/157864561-a3fb0035-cf82-4a21-bfc0-94314fd8f96a.mp4
- Check `Tfoot` `border-radius`
- Check `Tfoot`'s `Td` `border-top`
<details>
```markdown
```
</details>
=> feat: table empty layout improvements

.github/workflows/main.yml, .github/workflows/pr.yml, .github/workflows/release.yml
It was missing the build step in the release workflow, that's probably the reason why the packages are not working.
fixes #320
=> fix: add build to release workflow

index.ts
export Avatar
<details>
```markdown
```
</details>
=> feat: export avatar

components/Button/Button.themes.ts, components/Button/Button.tsx, components/Skeleton/Skeleton.stories.tsx, components/Skeleton/Skeleton.tsx
- closes #192 
Fixes an issue with button styles
<details>
```markdown
```
</details>
=> fix: button styles, cleanup themes

components/Dialog/Dialog.stories.tsx, components/Dialog/Dialog.tsx
- Closes https://github.com/traefik/faency/issues/323
Review should be enough
<details>
```markdown
```
</details>
=> fix: dialog elevation

components/IconButton/IconButton.stories.tsx, components/IconButton/IconButton.tsx
- adds contrast variant, updates story
<details>
```markdown
```
</details>
=> feat: IconButton, add contrast variant

components/Text/Text.stories.tsx, components/Text/Text.tsx
- closes https://github.com/traefik/faency/issues/202
<details>
```markdown
```
</details>
=> feat: Text, add weight variants

components/Alert/Alert.stories.tsx, components/Card/Card.stories.tsx, components/Heading/Heading.stories.tsx, components/Heading/Heading.test.tsx, components/Heading/Heading.themes.ts, components/Heading/Heading.tsx, components/Skeleton/Skeleton.stories.tsx, components/Table/Table.stories.tsx, index.ts, stitches.config.ts
- Closes https://github.com/traefik/faency/issues/234
- `Heading` component no longer exists
- headings are no longer linked to `Text` component, therefore they no longer share their variants
- puts back `transform` variants for headings
- headings no longer need `as` prop
<details>
```markdown
```
</details>
=> feat!: rework Heading

components/IconButton/IconButton.stories.tsx, components/IconButton/IconButton.tsx
- closes https://github.com/traefik/faency/issues/347
- closes https://github.com/traefik/faency/issues/174
https://user-images.githubusercontent.com/3367393/163997758-dacce9dc-6d51-4d07-8635-e28621cd2962.mp4
`IconButton` api changed and UI changed
<details>
```markdown
```
</details>
=> feat!: rework IconButton

components/Heading/Heading.tsx
Enforce no margins around each `Hx` element
<details>
```markdown
```
</details>
=> fix: headings, disable user agent stylesheet margins

LICENSE, README.md, package.json
Adds license [Apache 2.0](https://choosealicense.com/licenses/apache-2.0/)
Value in `package.json` follows [npm recommendations](https://docs.npmjs.com/cli/v7/configuring-npm/package-json#license), applying the SPDX OSI approved license ID, as visible [here](https://spdx.org/licenses/).
License was discussed and chosen with @ldez and @mmatur .
<details>
```markdown
```
</details>
=> chore: add license, Apache-2.0

.storybook/components/DocContainer.tsx, stories/colors.stories.tsx, stories/examples/dashboard.stories.tsx, stories/examples/form.stories.tsx
Some documentation stories relied on `Heading` component, which no longer exists
https://user-images.githubusercontent.com/3367393/165122976-a58a9a31-9364-4cc3-bdd7-6db3939f0060.mp4
https://user-images.githubusercontent.com/3367393/165122863-e243ac0c-3a57-4104-9835-65bd3b274478.mp4
<details>
```markdown
```
</details>
=> chore: doc stories, no longer rely on Heading obsolete component

components/Badge/Badge.tsx, components/Card/Card.tsx, components/Checkbox/Checkbox.tsx, components/Link/Link.stories.tsx, components/Select/Select.stories.tsx, components/Switch/Switch.themes.ts, components/Switch/Switch.tsx, components/Textarea/Textarea.tsx
- closes https://github.com/traefik/faency/issues/362
Now behaves like a button when interactive.
Outline color is "stronger" when element is focused.
https://user-images.githubusercontent.com/3367393/164496842-48e51e83-378e-4f04-9c1c-984bb5249590.mp4
Outline is 2px rather than 1px, I felt it was not visible enough, before.
Styles were not correctly applied, therefore the outline depending on the `variant` value was not applied.
Added outline around the button when it is focused. I felt elevation on the thumb was not visible enough.
Some cleanup while checking components and their stories.
Check stories for updated components:
- `Badge`
- `Card`
- `Switch`
Their `interactive` version should be tabbable and their focused state should be visible enough.
Please note I made decisions alone. …
=> feat: interactive components, improve focus outline

components/Badge/Badge.themes.ts, components/Badge/Badge.tsx
Add pressed state for Badge
Rename theme variables
https://user-images.githubusercontent.com/3367393/165502191-767a4338-d06f-455d-9c6e-47fabf27f12c.mp4
<details>
```markdown
```
</details>
=> feat: badge pressed state

components/Card/Card.tsx
- closes #370
See issue
<details>
```markdown
```
</details>
=> fix: Card Interactive, pressed behavior broken

components/Input/Input.tsx
Before:
https://user-images.githubusercontent.com/38889364/180120235-a1d95b6c-270b-4ab6-ad31-ae832f7d37f6.mov
After:
https://user-images.githubusercontent.com/38889364/180120226-796aefc8-3dcc-4d7a-92ae-38094184ac47.mov
=> fix: Input start adornment zIndex

index.ts
Export ButtonSwitch component from faency
=> fix: export ButtonSwitch component
