.travis.yml

The change remove the double build for PR from the main repo branches.

chore: limit the CI to master and tags

---

src/components/Heading.tsx

@matthieuh, I noticed that it seems we don't have 9 or 10 available for the `fontSize` property. So then I redistributed the sizes to be incremental from 3 to 8, which seems to be our biggest possible value, and equivalent to 72px. Thoughts?
This is the final result after this change:

Fix headings for sizes 4 and 5

---

lerna.json

**Reason:** Build is not triggered with tags like this one: `@containous/faency@0.4.0` due to the new monorepo architecture

fix: enable builds on *@*.*.* tags instead of v*.*.*

---

packages/website/src/components/PropsTable.js

I noticed that we have a possible field called `default` on the `PropsTable`, but it was not used when displaying the items.
I thought we could add it like this, what do you think?
If the value has no default, it just doesn't show it, like this:

Proposal: Add default value to Description column in Docs

---

.travis.yml
package.json
packages/faency/package.json
packages/faency/src/components/Button.test.tsx
packages/faency/src/components/Card.test.tsx
packages/faency/src/components/CardLink.test.tsx
packages/faency/src/components/Chip.test.tsx
packages/faency/src/components/DropdownMenu.test.tsx
packages/faency/src/components/FormMessage.test.tsx
packages/faency/src/components/Heading.test.tsx
packages/faency/src/components/Input.test.tsx
packages/faency/src/components/InputTags.story.tsx
packages/faency/src/components/InputTags.test.tsx
packages/faency/src/components/InputTags.tsx
packages/faency/src/components/Select.test.tsx
packages/faency/src/components/Text.test.tsx
packages/faency/src/hooks/use-click-outside.tsx
packages/faency/src/hooks/use-key-listener.tsx
packages/website/src/App.js
packages/website/src/components/CodeBlock.js
packages/website/src/components/Container.js
packages/website/src/components/Layout.js
packages/website/src/components/List.js
packages/website/src/components/MenuToggle.js
yarn.lock

> Removed test for InputTags temporarily due to Jest import error, opened issue #86 to handle this specific error
- Fixed tests by adding theme provider;
- Fixed warning by changing types on PropTypes for Docs website:
- Added `yarn test` script, only runs Fæncy tests for now; and
- Added `yarn test` to the Travis config file.

Fix tests and warnings on Docs website

---

packages/faency/src/components/Avatar.tsx
packages/faency/src/components/Box.tsx
packages/faency/src/components/Button.tsx
packages/faency/src/components/Card.tsx
packages/faency/src/components/Checkbox.tsx
packages/faency/src/components/Flex.tsx
packages/faency/src/components/FormMessage.tsx
packages/faency/src/components/InputTags.tsx
packages/faency/src/components/Loading.tsx
packages/faency/src/components/Nav/Nav.tsx
packages/faency/src/components/Nav/index.ts
packages/faency/src/components/Radio.tsx
packages/faency/src/components/Skeleton.tsx
packages/faency/src/components/SubNav.tsx
packages/faency/src/components/Tooltip/index.ts
packages/faency/src/index.ts

There were some type declarations that were not exported yet, so this PR exports all types from components and adds them to the Faency `index.ts`.

Export all types from Components and from Faency index

---

packages/website/src/components/PropRender.js

This PR fixes a bug on the propRender for Colors that was overriding the display `inline-flex` to `flex`.

Fix prop render for Colors

---

index.ts
stitches.config.ts

This PR aims to make it easier to import the `CSS` interface with all Stitches configuration defined by default.

chore: export CSS type with default config set

---

components/Card/Card.tsx

Add `cursor: 'pointer'` on hover for interactive card

fix: Card interactive, add cursor pointer

---

components/Input/Input.themes.ts
components/Input/Input.tsx
components/Select/Select.stories.tsx
components/Select/Select.themes.ts
components/Select/Select.tsx

This PR is not about applying the new Select design which will require us to create a custom Select component or wait for radix to provide a Select primitive.
This PR is about having consistency between the Input and the Select component.
Before:
After:

fix: select style consistency with input one

---

components/Navigation/Navigation.tsx

This PR fixes the alpha value for the NavigationItem in resting state (not active, not focused, not hovered).
Current: 
Expected:

fix: alpha value on Navigation Item resting state

---

components/Elevation/Elevation.tsx
components/Navigation/Navigation.tsx

Currently, we need to manually set the Background color for the components that use elevation, but we could set it along with the elevation style, which will help to have consistency as we won't need to remember setting the background color anymore.
Please let me know if you agree with the proposition, or if there's a scenario where you think it could become a problem.

proposal: set background color based on elevation

---

components/Input/Input.stories.tsx
components/Input/Input.tsx
components/TextField/TextField.tsx

On [TextField mockup](https://app.zeplin.io/project/61497d608f9b6e598e281a34/screen/61497eadad40de21822f2aac), Josep recommended to remove any hover/focus interaction for input adornments.
- Replaced IconButton by simple icons with cusor: pointer behaviour on hover
- Removed IconButton integration from input AdornmentWrapper
- Input stories, removed IconButton as adornment

fix: input adornments josep feedback

---

components/Select/Select.tsx

Select had slight visible border-radii when hovered, because pseudo elements applying layers of `background-color` didn't have border-radius aligned with parent.
Apply `border-radius: 'inherit'` on both `::before` and `::after` inside `SelectWrapper`
I show before/after with different colors to make it more visible. Note both `::before` and `::after` require the radius because they are layered one of top of the other.

fix: Select, before and after, inherit borderRadius

---

components/Card/Card.tsx
components/Dialog/Dialog.tsx
components/Elevation/Elevation.tsx
components/Input/Input.tsx
components/Menu.tsx
components/Navigation/Navigation.tsx
components/Popover/Popover.tsx
components/Select/Select.tsx
components/Switch/Switch.tsx
index.ts

exporting `elevationVariants` for external custom components to reuse variants when required.
Using `elevationVariants` or `Elevation` component depends on implementation choices Faency shouldn't make.

chore: export elevationVariants

---

components/Input/Input.tsx

Fixed inner `useImperativeHandle` inside `Input`, so that Radix tooltips can properly call `getClientBoundingRect` on them
Closes #211

fix: Input, pass DOM node through useImperativehandle

---

components/Overlay.tsx

Dialog overlay was not applying any background color.
Cause: wrong syntax for hsla computation
Closes #181 
https://user-images.githubusercontent.com/3367393/144429413-62802cb7-e37a-48ee-a5c1-d634967a19ab.mp4
https://user-images.githubusercontent.com/3367393/144429428-0b19bd7d-9aee-4bff-8cf5-c60764daaca7.mp4

Fix: dialog overlay broken

---

components/Dialog/Dialog.stories.tsx

In Dialog story, example was not properly using Dialog.
I updated the story, based on radix doc: https://www.radix-ui.com/docs/primitives/components/dialog#abstract-the-overlay-and-the-close-button
Consequences: focus is restored to the trigger button when dialog is closed
Test for yourself on the story

fix: Dialog story, proper use of Dialog and DialogTrigger

---

components/Badge/Badge.stories.tsx
components/Badge/Badge.themes.ts
components/Badge/Badge.tsx
package-lock.json
package.json

Cleaning up badge component, NB: this applies no design system changes. 
This will be done, hopefully in a future step.
- added missing compoundVariants programatically
- added all color variants in story programatically
- default color variant (`gray`) is duplicated to make sure it's clear to the user
- cleaned up theme file
- updated `rollup-plugin-typescript2` from `^0.29.0` to `^0.30.0` due to a build issue
- CI: https://github.com/traefik/faency/runs/4433331267?check_suite_focus=true
- https://github.com/alexjoverm/typescript-library-starter/issues/310#issuecomment-811451090

feat: badge cleanup

---

components/Select/Select.stories.tsx
components/Select/Select.tsx

Closes #239 
Apply to select:
```
overflow: 'hidden',
textOverflow: 'ellipsis',
whiteSpace: 'nowrap',
```
Better position for Caret with better spacing inside select.
Added a specific story for Select: `Overflow`
Tested on Chrome + Firefox
https://user-images.githubusercontent.com/3367393/147371779-645adc1c-8c74-403b-94af-00eba54412c6.mp4

fix: [Select] selected option overflows, better caret position

---

components/Input/Input.stories.tsx
components/Label/Label.stories.tsx
components/TextField/TextField.stories.tsx
utils/ignoreArgType.ts

Inputs and their Labels are now binded through `htmlFor` + `id` combinations. Hence, they require unique ids inside both "canvas" and "docs" modes.
Closes #210
Rework `Input` and `Label` bindings in all related stories:
- Input
- Label
- TextField 
Added a helper `ignoreArgType`  to shorten hiding the `id` arg I had to pass to template stories and their duplicates.
:warning: I noticed that each story title held an `id` which may conflict with ids we set inside stories.
There's an issue calling for improvements on that subject: #208

Fix: labels binding in stories

---

components/Label/Label.stories.tsx
components/Text/Text.stories.tsx
components/Text/Text.tsx

Closes #242 
`transform="capitalize"` now capitalizes only first letter.
Adds `transform="capitalizeWords"` in case previous behaviour may be of any use.
Updates stories for `Text` and `Label`
:warning: Added as comment in `Text`: this will only work with block elements (display block/inline-block)
Overriding `Text` or `Label` display might conflict with this variant
[source](https://developer.mozilla.org/en-US/docs/Web/CSS/::first-letter)

Fix: label all letters capitalized

---

components/Table/Table.stories.tsx
components/Table/Table.tsx

`Th` extends `Label` styles and variants.
When `transform='capitalize'` default variant is applied to `Th`, style `display: 'inline-block'` takes precedence.
It breaks table layout.
I reset `display: 'table-cell'` from inside `Th` to correct this behaviour.
What would you prefer?
1. Removing this enforced display value from `Text`, which could lead to unexpected bugs with `capitalize` when display does not match a block level, but removes the extra logic inside `Th`
2. Doing as I proposed

Fix: label capitalize breaking th layout

---

components/Accordion/Accordion.tsx
components/Radio/Radio.tsx
components/RadioAccordion/RadioAccordion.stories.tsx
components/RadioAccordion/RadioAccordion.tsx
components/RadioAccordion/index.tsx
index.ts

Adds `RadioAccordion` component, following mockup
It depends on both `Accordion` and `Radio` styling.
It replaces the default `Chevron` inside `Accordion` with a decoration looking like a radiobutton: it's not an interactive input, it just reproduces the UI of `Radio`.
`RadioAccordion` enforces having a single panel open at a time, plus disables collapsing open panels.
See Radix primitive [Accordion](https://www.radix-ui.com/docs/primitives/components/accordion)
NB: currently `Accordion` exports `AccordionTrigger` as the default UI element, internally rendering an animated chevron. Customizations require exporting `StyledAccordionHeader` and `StyledAccordionTrigger`.
https://user-images.githubusercontent.com/3367393/150810532-4ba13408-71c7-40f4-9d5c-372a70a882fd.mp4
- Why not using a real …

feat: radio accordion

---

components/TextField/TextField.stories.tsx
components/TextField/TextField.tsx
components/Tooltip/Tooltip.stories.tsx

TextField, allow `label` prop to be a Component.
The initial need is to allow nesting more elements than the field's label next to the label, such as tooltips and popovers.
A `ReactNode` could also make sense, but it would lose the bindings to the input internal state, which ensures a good UX.
I created a specific type for the `TextFieldLabelProps`, because they represent the requirement for any label component.
https://user-images.githubusercontent.com/3367393/151402668-5179c4b7-7651-4e92-b61a-ac06b69addbb.mp4

Feat: textfield allow component label

---

components/Label/Label.stories.tsx
components/Switch/Switch.stories.tsx
components/Text/Text.stories.tsx
components/Text/Text.themes.ts
components/Text/Text.tsx
components/TextField/TextField.tsx
components/Textarea/Textarea.tsx

Improve field label behaviour and simplify label color computation.
Until now, `TextField` was applying conflicting rules to its `Label`, for instance:
- `variant: 'red'` + `invalid` when it was invalid
- `variant: 'subtle'` + `disabled` when it was disabled
Expectations where mislead by this and the result did not match them.
Check `Label`, `Text`, `TextField`, `Textarea` and `Switch` stories 
Reworked text variants related to label behavior inside forms:
- disabled label
- invalid label
Instead of having separate variants, I merged them together inside `variant`
Added stories.
Added stories to follow `Text` changes and display some implementations we made in other places.
Updated `TextField` label props accordingly
Update `Textarea` label props accordingly
I noticed I didn't write …

Feat!: improve field label behavior

---

components/RadioAccordion/RadioAccordion.tsx

`collapsible` and `type` props should not be allowed, nor required for `AccordionRoot`

fix: radio accordion root, props should not include collapsible

---

components/AriaTable/AriaTable.stories.tsx
components/AriaTable/AriaTable.tsx
components/AriaTable/index.ts
components/Link/Link.tsx
components/Table/Table.stories.tsx
index.ts
package-lock.json
package.json

- Adds an ARIA-role based table
- all its structure is made of `div`s and `span`s with proper roles and `display` 
- Adds an unstyled link component
- Adds similar stories as `Table`
- Adds a story showing how to build links as table rows
All recommendations and best practices I read where explicitly telling to avoid using an Aria Table unless other layouts are impossible.
My use case justifying this component over the basic `Table` is to allow having links as table rows.
There are some workarounds as described [here](https://robertcooper.me/post/table-row-links), but in the end, this implementation seems the most accessible outcome for my specific use case.
WAI-ARIA
- [wai-aria practices](https://www.w3.org/TR/wai-aria-practices/#table)
- [table …

Feat: aria table

---

components/Table/Table.stories.tsx
components/VisuallyHidden/VisuallyHidden.stories.tsx
components/VisuallyHidden/VisuallyHidden.tsx
components/VisuallyHidden/index.tsx
index.ts
package.json

Add VisuallyHidden primitive
Give accessible examples of tables with a title.
3 Options:
1. Display caption and style it
2. Display a title not child of table + duplicate title with a visually hidden caption
3. Display a title not child of table + link through `aria-describedby` attribute on table 
Option 2 is recommended over Option 3 [here](https://www.w3.org/WAI/tutorials/tables/caption-summary).
See https://www.w3.org/WAI/tutorials/tables/caption-summary
| Dependency | Version        | State   |
| ---------- | -------------- | ------- |
| `@radix-ui/react-visually-hidden`       | 0.1.3          | Added   |
Added [`@radix-ui//react-visually-hidden`](https://www.radix-ui.com/docs/primitives/utilities/visually-hidden) to allow hiding some accessibility-driven dom nodes which are not …

feat: visuallyHidden + table accessible examples

---

components/Table/Table.stories.tsx
components/Table/Table.tsx

Fixes the overlay `border-radius` for tables headers and footers.
Before:
After:

fix: inherit `border-radius` on table children elements

---

stitches.config.ts

Make sure media breakpoints from config don't overlap (related to https://github.com/modulz/stitches/issues/901)
Split PR from https://github.com/traefik/faency/pull/232

feat: improve breakpoints overlapping

---

components/TextField/TextField.stories.tsx

Adds story example for readonly copy use case.

feat: TextField, ReadonlyCopy story

---

components/Textarea/Textarea.stories.tsx
components/Textarea/Textarea.tsx

Recent mockup required that a `Textarea` allows an `endAdornment`.
Adds stories for this example
https://user-images.githubusercontent.com/3367393/154340513-a3a62063-2d01-421d-a23d-c271109dca08.mp4

feat: Textarea, add endAdornment

---

components/Skeleton/Skeleton.stories.tsx
components/Skeleton/Skeleton.tsx

Closes #227 
Adds inference for Typographies and Children of Skeleton.
Reworks variants to handle borderRadii of different child UI elements which would be passed as children.
https://user-images.githubusercontent.com/3367393/146262318-ac20f9a4-4a1e-4c15-8aa4-11dc7739be32.mp4
- `avatarX` variants (1 to 6)
- `title`
- `heading`

feat!: skeleton infer dimensions

---

.github/workflows/pr_title.yml
package-lock.json
package.json

Need: Secure commit messages to ensure semantic-release workflow will work.
Adds a Github action to check PR title conforms with [conventional-commits](https://www.conventionalcommits.org/en/v1.0.0/)
The action logs nothing if the check passes, else logs errors.
PR split from https://github.com/traefik/faency/pull/288
- https://github.com/marketplace/actions/semantic-pull-request
Because we work on a fork-based repo, we must trigger the action on `pull_request_target`, because the GH action runs `octokit` calls with a token. More info on the repo:
- https://github.com/amannn/action-semantic-pull-request#event-triggers
- https://github.com/amannn/action-semantic-pull-request/issues/139
GH actions:
- https://github.com/marketplace/actions/conventional-commits-pr seems less efficient
- …

feat: add GitHub action pr title check b

---

components/Popover/Popover.stories.tsx
components/Popover/Popover.tsx
index.ts

Closes #315 
- Popover arrow customizable
- also export [PopoverAnchor primitive](https://www.radix-ui.com/docs/primitives/components/popover#anchor)
- adds stories
<details>
```markdown
```
</details>

fix: popover arrow color not customizable

---

components/Dialog/Dialog.stories.tsx
components/Dialog/Dialog.tsx
index.ts

We have use cases for dialogs which cannot be closed.
Adds export of dialog's content without the close button for easier composition towards that end.
- `DialogClose` component is now the styled version of the primitive
<details>
```markdown
```
</details>

feat!: dialog export content without close icon

---

package.json

Adds missing info related to issues and the project to the `package.json`.

chore: add project info to package.json

---

components/Text/Text.stories.tsx
components/Text/Text.tsx

Text component had no `inherit` feature.
- add `variant="inherit"`
- add `size="inherit"`
- updated variant and size stories to display inherit feature

feat: Text component, add inherit variants for fontSize and color

---

components/AriaTable/AriaTable.stories.tsx
components/AriaTable/AriaTable.tsx
components/Table/Table.tsx

Add `fullColSpan`  boolean prop to `AriaTd`, so that we can span a single column inside a whole table footer. 
Previously, Footer content was not spanning fully, this behavior stayed unnoticed.
After some trials, I ended up with an absolute position hack to ensure the cell always spanned the full footer.
Implementing the `colSpan` behavior is too complex for the need, that's why I went for a hack.
a11y-wise, the hidden cell is also hidden from the accessibility tree, as [MDN states](https://developer.mozilla.org/en-US/docs/Web/CSS/visibility#accessibility_concerns). 
For top-notch a11y, it would be nice that implementors precise `aria-colspan`, as shown in the stories.
Computing that value is really tricky on complex tables, hence I'm in favor of letting users setting this attribute …

feat: aria table colspan

---

components/AriaTable/AriaTable.stories.tsx
components/Table/Table.tsx

User agents on firefox and chrome enforce `verticalAlign: 'inherit'` for table rows (`tr`) and cells (`td`, `th`), and enforce `verticalAlign: 'middle'` for row groups (`thead`, `tbody`, `tfoot`).
This PR ensures this is set by default.
For `Aria` variants of the `Table`, this allows not depending on user agent and implementing the same default behavior.
- chrome
- firefox
When cell content has different sizes, everything will therefore be centered.
<details>
```markdown
```
</details>

fix: table default alignment

---

.storybook/components/DocContainer.tsx

`FaencyProvider` was not wrapping all stories at once when in doc mode, resulting in `IdProvider` rendering duplicate ids for some components:
- tooltip
- label/input
Docs addon describes a recipe to wrap the whole doc with a provider: https://github.com/storybookjs/storybook/blob/next/addons/docs/docs/recipes.md#overwriting-docs-container
Unfortunately, "canvas" mode doesn't share the same global rendering as "docs" mode. "docs" mode renders each canvas in a global doc, resulting in `FaencyProvider` wrapping duplication. So far, it doesn't seem to be a problem, but I'd like your feedback on that.
Changes:
- solve the previous issue
- don't break behaviour in "canvas" mode
- duplicate `FaencyProvider` wrapping in "docs" mode:
I added a `<div className="toto">` inside the `FaencyProvider` …

fix: DocContainer, wrap with FaencyProvider

---

components/Skeleton/Skeleton.stories.tsx
components/Skeleton/Skeleton.tsx

Previously, the layout of a `Bubble` was not properly inferred by the Skeleton, because it did not handle inline layout properly.
Improves inferred display of `Skeleton` by enforcing children to `display: 'block'`, instead of enforcing the `Skeleton` to `display:'inline-flex` for possibly inline children.
Added BubbleInferred and CustomInferred stories.
Bubble inferred layout previously was what happens when I disable the display styling.
https://user-images.githubusercontent.com/3367393/162942042-b9b3b5e4-ae2b-4305-921b-7393b521384d.mp4
<details>
```markdown
```
</details>

feat: Skeleton, improve inferred display

---

components/Badge/Badge.stories.tsx
components/Badge/Badge.test.tsx
components/Badge/Badge.tsx

- Closes #351 
I chose to implement `asChild` behavior instead of `as` prop, which is really difficult to handle when we implement components on top of `styled`.
Also this choice follows the following RFC:
- https://github.com/traefik/faency/issues/218
usgae of `as` prop is not disabled by this PR, simply, we cannot handle polymorphic typing properly. Users can still remove types from the component and make use of `as` prop if they prefer.
Added test and story to back the use case of a "BadgeLink"
I consider this change non-breaking, because as the issue states, there was an unexpected breaking change brought by https://github.com/traefik/faency/commit/b2851f5c542488e2176185505210db9c75699e5d, which removed `as` prop and  stitches' polymorphic typings. Do you think we should consider this …

feat: badge `asChild`

---

components/Button/Button.stories.tsx
components/Button/Button.test.tsx
components/Button/Button.tsx

- Closes #107 
I chose to implement `asChild` behavior instead of `as` prop, which is really difficult to handle when we implement components on top of `styled`.
Also this choice follows the following RFC:
- https://github.com/traefik/faency/issues/218
usgae of `as` prop is not disabled by this PR, simply, we cannot handle polymorphic typing properly. Users can still remove types from the component and make use of `as` prop if they prefer.
Added test and story to back the use case of a "ButtonLink"
I also reworked `state="waiting"` implementation, so it doesn't clash with `asChild` behavior.
https://user-images.githubusercontent.com/3367393/163158384-7af0ccbd-cb24-4650-a15e-dbe4313fb65f.mp4
<details> …

feat: button `asChild`
